### PR TITLE
Feature 252 partial search

### PR DESCRIPTION
**Pull request by MrGold6**
Need a lot of testing with:
- partial search
- reset
- pagination

### CODE REVIEW

**Review by Camper689 — COMMENTED** [review]
- If you're on second page and make search request, results are not shown.
- Reset button is too big. Should add btn-sm class
- Input fields are too blank, add placeholders
- IsActive field always resets to unchecked, need to change to checked
- Search row must be highlighted, add table-secondary class to this row

**Review by Camper689 — APPROVED** [review]
Great

**Comment by PavelHorishny** [comment]
Screenshot from 2022-05-22 17-50-56
Maybe should show less items per page
Screenshot from 2022-05-22 17-49-59
Screenshot from 2022-05-22 17-50-23
If "IsActive" isn't selected there's no search results

**Review by JohnnyMahoney — APPROVED** [review]

**Review by PavelHorishny — APPROVED** [review]
I meant that if I want to find someone by name why should I know if he is active or not.

**Pull request merged**
